### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-elisamartinb#1]
Awesome job @elisamartinb  !!!

Here you have some tips to improve the exercise:

- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document
- [x] Remove the call of `getRandomNumber` on line 15, you aren't using it!
- [x] Extract the feedback painter to a function
- [x] Improve readability of if/else
- [x] For the last statement on if/else, a simple `else` is enough
- [x] Move variables declaration to the top of the file
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Remove commented code

Let me know if you have any doubts ;)

Go for it!!

**Comment by elisamartinb** [comment]
Done @nasivuela !!😁

**Comment by nasivuela** [comment]
Well done @elisamartinb !!

![](https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif)

I'm closing this, but if you want to improve it even more, here you have some ideas:
- Write a number and hit enter, something is not working :S 
- Add a reset functionality
- Let users play from their phones!
